"""What the robot says when something breaks.

Failures are social events, not technical ones. A person standing in front of a desk
robot should hear a person-shaped sentence, while the stack trace goes to the log.

These strings are intentionally *not* generated by the LLM: the LLM is frequently the
thing that just failed, and a fallback that depends on the failed component is not a
fallback. They are also intentionally not in the Role Packs — every deployment needs
them, and a role author forgetting to define one would produce silence.
"""

from __future__ import annotations

from backend.emotion import Expression
from backend.errors import ErrorCategory

#: Per-category, per-language. `en` is the fallback language when the detected language
#: is unknown or unsupported.
_FALLBACK_SPEECH: dict[ErrorCategory, dict[str, str]] = {
    ErrorCategory.STT_EMPTY: {
        "en": "Sorry, I didn't catch that. Say it again?",
        "fa": "ببخشید، متوجه نشدم. دوباره می‌گی؟",
    },
    ErrorCategory.STT_FAILED: {
        "en": "Sorry, I had trouble hearing that. Could you try again?",
        "fa": "ببخشید، خوب نشنیدم. می‌شه دوباره بگی؟",
    },
    ErrorCategory.STT_TIMEOUT: {
        "en": "Sorry, that took too long to hear. Try me again?",
        "fa": "ببخشید، شنیدنش طول کشید. دوباره امتحان می‌کنی؟",
    },
    ErrorCategory.LLM_FAILED: {
        "en": "Hmm, I had trouble thinking about that. Could you try again?",
        "fa": "هوم، نتونستم فکرم رو جمع کنم. می‌شه دوباره بپرسی؟",
    },
    ErrorCategory.LLM_TIMEOUT: {
        "en": "Sorry, I got lost in thought there. What were you saying?",
        "fa": "ببخشید، تو فکر فرو رفتم. چی می‌گفتی؟",
    },
    ErrorCategory.LLM_EMPTY: {
        "en": "I'm not sure what to say to that. Tell me more?",
        "fa": "نمی‌دونم چی بگم. بیشتر برام بگو؟",
    },
    ErrorCategory.TTS_FAILED: {
        "en": "Sorry, my voice glitched. One more time?",
        "fa": "ببخشید، صدام قطع شد. یک بار دیگه؟",
    },
    ErrorCategory.TTS_TIMEOUT: {
        "en": "Sorry, my voice took too long. Try again?",
        "fa": "ببخشید، صدام دیر شد. دوباره امتحان کن؟",
    },
    ErrorCategory.INTERNAL: {
        "en": "Something went wrong on my side. Let's try that again.",
        "fa": "یک مشکلی پیش اومد. بذار دوباره امتحان کنیم.",
    },
}

#: The face that accompanies each failure. Confusion reads as "I didn't understand";
#: it is friendlier than an error icon and, unlike one, it is honest.
_FALLBACK_EXPRESSION: dict[ErrorCategory, Expression] = {
    ErrorCategory.STT_EMPTY: Expression.CONFUSED,
    ErrorCategory.STT_FAILED: Expression.CONFUSED,
    ErrorCategory.STT_TIMEOUT: Expression.CONFUSED,
    ErrorCategory.LLM_FAILED: Expression.CONFUSED,
    ErrorCategory.LLM_TIMEOUT: Expression.CONFUSED,
    ErrorCategory.LLM_EMPTY: Expression.CURIOUS,
    ErrorCategory.TTS_FAILED: Expression.CONFUSED,
    ErrorCategory.TTS_TIMEOUT: Expression.CONFUSED,
    ErrorCategory.INTERNAL: Expression.CONFUSED,
}

_DEFAULT_LANGUAGE = "en"


def fallback_speech(category: ErrorCategory, language: str | None = None) -> str:
    """A natural sentence for this failure, in the person's language where known."""
    by_language = _FALLBACK_SPEECH.get(category, _FALLBACK_SPEECH[ErrorCategory.INTERNAL])
    return by_language.get(language or _DEFAULT_LANGUAGE, by_language[_DEFAULT_LANGUAGE])


def fallback_expression(category: ErrorCategory) -> Expression:
    """The face to show for this failure."""
    return _FALLBACK_EXPRESSION.get(category, Expression.CONFUSED)
